---
name: Upload Release Asset
on:
  release:
    types:
      - released
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Container start
        run: docker-compose up -d

      - name: Test on AmazonLinux 2023
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T amazonlinux2023 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"

      - name: Test on RedHat 8
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T redhat-ubi8 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"

      - name: Test on RedHat 9
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T redhat-ubi9 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"

      - name: Test on Ubuntu 22.04
        # Add an option "-T" as a countermeasure for the error "the input device is not a TTY"
        run: docker-compose exec -T ubuntu22.04 sh -c "cd /usr/local/src/my-shell-scripts && shellspec"

      - name: Container stop
        run: docker-compose down

      - name: Build project
        run: |
          mkdir ${{ github.event.repository.name }}-${{ github.ref }}
          cp -r ./bin ./lib LICENSE README.md ${{ github.event.repository.name }}-${{ github.ref }}
          tar zcvf ${{ github.event.repository.name }}-${{ github.ref }}.tar.gz ${{ github.event.repository.name }}-${{ github.ref }}

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-${{ github.ref }}.tar.gz
